### PR TITLE
Flush

### PR DESCRIPTION
**Pull request by khou2020**
FIx make check fail on large file test.
Fix buffer init bug on flushing when more than 1 round required.
Change large_coalease to work with BB.

### CODE REVIEW

**Comment by wkliao** [comment]
merge nc4 branch into flush and see if there is any conflict.

**Comment by khou2020** [comment]
Conflicts solved

**Comment by wkliao** [comment]
FAIL: large_coalesce
% more large_coalesce.log 
---- set PNETCDF_SAFE_MODE 0
*** TESTING C   large_coalesce for skip filetype buftype coalesce  ------ Error at line 199 in large_coalesce.c: (NC_EMAX_REQ)
0 (at line 209): expect buf[1073741814]=97 but got 0
0 (at line 209): expect buf[1073741815]=98 but got 0

**Comment by khou2020** [comment]
fixed

**Pull request merged**
