### PR TITLE
fix hash_map

### PR DESCRIPTION
**Pull request by khou2020**
fix table not initialized problem in hashmap.
fix using built in comm_split_type on MPI 3.

### CODE REVIEW

**Comment by wkliao** [comment]
Why not just use NCI_Calloc when allocating map->table?

**Comment by wkliao** [comment]
Travis CI build failed.

**Comment by khou2020** [comment]
I accidentally committed my testing Makefile.am. Restored.

**Comment by khou2020** [comment]
A problem in shared file still need fixing

**Pull request closed without merging**
