### PR TITLE
Added absolute- and relative- tolerances.

### PR DESCRIPTION
**Pull request by cponder**
I don't think the original version of this file is the same as the trunk version, so it may be a dirty merge.

### CODE REVIEW

**Comment by wkliao** [comment]
Shouldn't the OR at lines 126 and 138 be AND instead?
i.e. when both difference and ratio are smaller than
the thresholds, it continues to check the next variable element.

**Comment by wkliao** [comment]
When neither command-line option -t nor -r is used, the original behavior
should run, i.e. ncmpidiff stops when the first different element is found.
This should be an easy fix.

**Comment by cponder** [comment]
*On 7/13/19 8:05 PM, Wei-keng Liao wrote:*
>
>     Shouldn't the OR at lines 126 and 138 be AND instead?
>     i.e. when both difference and ratio are smaller than
>     the thresholds, it continues to check the next variable element.
>
Actually, no -- I don't want to flag a difference if the two elements 
fit inside either tolerance.
I'm trying to ignore these two cases:

1. X & Y are off by a large factor, but the two values are small, so I 
set a small absolute tolerance.
For example, weather predictions of 1mm vs 2mm of snow.
It would matter a *lot* if it was 1ft versus 2ft of snow, so I don't use 
a relative tolerance here.

2. X & Y are off by a larger difference, but their values are huge, so I 
set a small relative tolerance.
For example, wind velocities of 100 versus 120 MPH.

So if either tolerance will fit, then I skip that comparison and go onto 
the next.
I'd have poor experience with some other comparators that only allow me 
to set one or the other.
And I'd end up with useless comparisons, like above, where the factor 
differences only showed me tiny numbers that didn't matter.
And the absolute differences only showed me huge numbers where the 
differences didn't matter at that scale.

Thank you very much for accommodating this.
It's also handy that the comparators are rolled in with the regular 
PNetCDF build.
I manage I/O libraries (with Lmod) on several systems, and it reduces 
the number of components that I have to expose to the user.
WIth NCCMP I had to build it as a separate tool, dependent on the MPI & 
NetCDF builds, so it just added to the clutter.
And couldn't be used on the head-node because of all the dependencies!
With your tools I can build a separate copy of the cdfdiff to work in 
the base environment of the head-node.

 ?????? ?????? -- Carl

**Comment by cponder** [comment]
*On 7/13/19 8:11 PM, Wei-keng Liao wrote:*
>
>     When neither command-line option -t nor -r is used, the original
>     behavior
>     should run, i.e. ncmpidiff stops when the first different element
>     is found.
>     This should be an easy fix.
>
Yeah -- sorry about that, I was focused on getting the tolerances to work.
By default, my changes would make it report the element with the largest 
absolute difference, which is the most useful case to me.
(But it also requires scanning the whole array).
I would look at the values and then decide (based on the magnitude of 
the values) whether to use a relative or absolute tolerance to ignore it.
I believe I would get this same effect by explicitly setting -a 0.0 -r 
0.0 anyway, and leave the original default behavior the same.
Thanks,

 ?????? ?????? ?????? ?????? ?????? Carl

**Comment by wkliao** [comment]
This sounds to me both options -t and -r must be used together. It makes no sense in your
case that only one of them is used. I suggest to combine them into one option, such as
`-t 12.34,0.5`. This command-line option `-t` requires 2 values separated by a comma with
absolute difference as the former and ratio the latter. Let me know if this works for you.

**Comment by wkliao** [comment]
FYI. If you are going to revise the codes of this pull request, below are some git commands to do so.
* On you local machine, make sure you are on branch `master` by running command `"git branch"`
* Edit file `ncmpidiff.c, make changes, and save it once done
* Run command `"git add ncmpidiff.c"`
* Run command `"git commit --amend"`
* This will open the default editor, such as "vi". You can revise the previous commit message.
* Save and quit the editor.
* Run command `"git push --force origin master"` to push to your repo at github

**Comment by cponder** [comment]
*On 7/14/19 5:50 PM, Wei-keng Liao wrote:*
>
>     This sounds to me both options -t and -r must be used together. It
>     makes no sense in your
>     case that only one of them is used. I suggest to combine them into
>     one option, such as
>     |-t 12.34,0.5|. This command-line option |-t| requires 2 values
>     separated by a comma with
>     absolute difference as the former and ratio the latter. Let me
>     know if this works for you.
>
I'm ok with that, since using 0.0 for either one will make it act like 
only the other one has an effect.
Can you make the change?
Also you may want to pick your own name for the flag, though "-t" for 
"tolerance" sounds good to me.
Thanks,

 ???????????????????????????????????? Carl

**Comment by wkliao** [comment]
Options -a and -r are now combined into -t.
I also revised the difference report style.
Below is an example output.
```
% ./ncmpidiff -t 1,19 result.nc result.reference.nc
DIFF: global attribute "history" length (32) != (31)
DIFF: global attribute "file_id" of type "NC_CHAR" differs first at element 0
DIFF (tolerance): variable "ru" of type "NC_FLOAT" max at element [1, 53489, 0] of value 0.017854 vs 17.661091
DIFF (tolerance): variable "ru_save" of type "NC_FLOAT" max at element [1, 53667, 2] of value 0.002667 vs 16.549225
DIFF (tolerance): variable "ruAvg" of type "NC_FLOAT" max at element [1, 53667, 2] of value 0.009371 vs 16.588402
DIFF (tolerance): variable "ruAvg_split" of type "NC_FLOAT" max at element [1, 53667, 2] of value 0.028112 vs 49.765205
```

**Comment by cponder** [comment]
*On 7/10/19 12:22 AM, Wei-keng Liao wrote:*
>
>     I am still checking your changes for ncmpidiff. As for cdfdiff, it
>     will require more work, because the data may need to be
>     byte-swapped before calculating the difference, in which byte-swap
>     is not implemented in cdfdiff.
>
*On 7/15/19 11:46 AM, Wei-keng Liao wrote:*
>
>     Options -a and -r are now combined into -t.
>     I also revised the difference report style.
>     Below is an example output.
>
>     |% ./ncmpidiff -t 1,19 result.nc result.reference.nc DIFF: global
>     attribute "history" length (32) != (31) DIFF: global attribute
>     "file_id" of type "NC_CHAR" differs first at element 0 DIFF
>     (tolerance): variable "ru" of type "NC_FLOAT" max at element [1,
>     53489, 0] of value 0.017854 vs 17.661091 DIFF (tolerance):
>     variable "ru_save" of type "NC_FLOAT" max at element [1, 53667, 2]
>     of value 0.002667 vs 16.549225 DIFF (tolerance): variable "ruAvg"
>     of type "NC_FLOAT" max at element [1, 53667, 2] of value 0.009371
>     vs 16.588402 DIFF (tolerance): variable "ruAvg_split" of type
>     "NC_FLOAT" max at element [1, 53667, 2] of value 0.028112 vs
>     49.765205|
>     ||
>
Wei-keng -- I'm looking at updating the code for the SPEC benchmark, 
that uses this comparator for validation.
I'd rather use the cdfdiff than the ncmpidiff, since it simplifies the 
build & run setup.
Do you think you'd have it done in another month or 2?
Thanks,

                    Carl


-----------------------------------------------------------------------------------
This email message is for the sole use of the intended recipient(s) and may contain
confidential information.  Any unauthorized review, use, disclosure or distribution
is prohibited.  If you are not the intended recipient, please contact the sender by
reply email and destroy all copies of the original message.
-----------------------------------------------------------------------------------

**Comment by wkliao** [comment]
I will take a look.

**Comment by wkliao** [comment]
Hi, @cponder 
The same command-line option `-t` in `ncmpidiff` has also been added to utility program `cdfdiff`  in commit 5815de470dc244bb737b9084b2470f6af5305a7c
Please give it a try and let me know if it works out for you.

**Comment by cponder** [comment]
*On 10/13/19 5:35 PM, Wei-keng Liao wrote:*
>
>     Hi, @cponder <https://github.com/cponder>
>     The same command-line option |-t| in |ncmpidiff| has also been
>     added to utility program |cdfdiff| in commit 5815de4
>     <https://github.com/Parallel-NetCDF/PnetCDF/commit/5815de470dc244bb737b9084b2470f6af5305a7c>
>     Please give it a try and let me know if it works out for you.
>
Wei-keng -- I've been using the cdfdiff and like it a lot.
Thanks for making the changes for us!

         -- Carl


-----------------------------------------------------------------------------------
This email message is for the sole use of the intended recipient(s) and may contain
confidential information.  Any unauthorized review, use, disclosure or distribution
is prohibited.  If you are not the intended recipient, please contact the sender by
reply email and destroy all copies of the original message.
-----------------------------------------------------------------------------------

**Pull request merged**
