### PR TITLE
enable data log 8 Mib aligning

### PR DESCRIPTION
**Pull request by khou2020**
Align data log I/O to 8MiB boundary.

### CODE REVIEW

**Comment by wkliao** [comment]
can you explain more about this PR?

**Comment by khou2020** [comment]
It buffers data log data to make sure I/O is aligned with 8MiB stripe boundary.
Data log write will be done in the unit of 8MiBs if possible. The remaining part of the data will be buffered, waiting to be combined with the next entry.

**Comment by wkliao** [comment]
Any significant performance difference?
Is this applied to both blocking and nonblocking writes?

**Comment by khou2020** [comment]
I didn't test it. It will be test along with other optimizations.
It is for data log, which is used by both blocking and nonblocking requests.

**Comment by wkliao** [comment]
If the log I/O is done by one file per process, then I don't think such alignment will make any difference. Please evaluate the performance difference.

If there is no performance difference, I prefer no delay, i.e. write to log file immediately. That way data is more secured.

**Comment by khou2020** [comment]
experiment shows little improvement from aligning.

**Pull request closed without merging**
